### ISSUE TITLE
[auction-sponsored-transactions] Additional improvements

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#36]
**Tasks**
- [x] Simplify `ccd-js-gen` integration with the browser wallet once https://github.com/Concordium/concordium-node-sdk-js/pull/324 is merged and a new release of the `ccd-js-gen` tool is available. Remove hardcoded schemas from the front end.
- [ ] Use `ContractClient` from the Rust SDK to simplify the interactions with the contract at the backend https://github.com/Concordium/concordium-dapp-examples/pull/32#discussion_r1447381342
- [ ] Instead of a hardcoded node connection at the front-end to construct the grpc client, use the node connection provided from the connected wallet.
- [ ] Consolidate steps 4 and 5, so that no `signerAccount` has to be inputted in the input field anymore. The  `signerAccount`  can be stored in a `useState` hook at the point the signature is generated. This will minimize user error.
