### ISSUE TITLE
Rust event indexer for the track-and-trace contract

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#50]
**Task description**

The task is to develop an example implementation of an event indexer written in Rust. 

The events from the `track-and-trace` smart contract will be indexed to serve the historical item statuses to the front end. The indexer starts processing old events and then listens for new events that are coming in as the blockchain progresses. The indexer should be configurable to start indexing at a specific time (usually the time around when the smart contract was deployed). The indexer should store `checkpoints` (`block_height`, `transaction_hash`, and `event_index`) of the current event being processed to aid in debugging and to aid in re-starting the index from the persistent database in case the indexer crashed unintentionally.

The indexer runs a PostgreSQL database at the backend.

There are three tables in the database:
- `setting` for global settings and the checkpoints.
- `item_created_events` for all the item-created events logged by the contract.
- `item_status_changed_events` for all the item-status-changed events logged by the contract.

Smart contracts:
https://github.com/Concordium/concordium-rust-smart-contracts/issues/387#issue-2097981242
https://github.com/Concordium/concordium-dapp-examples/tree/main/trackAndTrace

**Sub-tasks**
- [x] Develop an indexer to process events from the blockchain and input them into the PostgreSQL database.
- [x] Develop an http server that provides two entrypoints for the front end to query the database:
      - [x] `GetItemStatusChangedEvents` by `item_id` returns a list of all status-changed events for specified `item_id` or an empty list if the item does not exist.
      - [x] `GetItemCreatedEvent` by `item_id` returns the event when the item was created or `None` if the item does not exist.

*Add label for component and priority.*
