### ISSUE TITLE
Add CIS3 (sponsored transaction) to the track-and-trace contract.

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#52]
**Task description**

The `change_item_status` entrypoint in the track-and-trace contract should be able to be invoked via the sponsored transaction mechanism.
https://github.com/Concordium/concordium-dapp-examples/blob/main/trackAndTrace/smart-contract/src/lib.rs#L525

Similar smart contracts with sponsored transaction design can be used as a reference e.g.:
https://github.com/Concordium/concordium-rust-smart-contracts/tree/main/examples/cis2-multi/src
https://github.com/Concordium/concordium-rust-smart-contracts/tree/main/examples/cis3-nft-sponsored-txs

**Sub-tasks**
- [x] Add `permit` entrypoint (https://proposals.concordium.software/CIS/cis-3.html)
- [x] Add `supportsPermit` entrypoint (https://proposals.concordium.software/CIS/cis-3.html)
- [x] Add test cases. The signature is generated inside the test case as a reference:
https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-multi/tests/tests.rs#L1159
