### ISSUE TITLE
Track And Trace Front End

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#61]
**Task description**

The track and trace front end should connect the different components.

**Sub-tasks**
- [x] Allow the admin to change roles and create items.
- [x] Allow whitelisted addresses to change the status of an item and submit a sponsored transaction to the backend.
- [x] Display the history of the statuses of an item as an explorer using the values stored in the Postgres database (the indexer has to index these historical events first).
