### ISSUE TITLE
Track-and-trace dapp improvements

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#75]
**Task description**
Summary of improvements for the `track-and-trace` dapp:

**Sub-tasks**
- [x] Display version at the front end.
- [x] Add link at front-end to the source code repo.
- [x] Generalize the state machine so that we can easily add/remove new addresses to be producer/seller/... via the front end.
- [x] Enable updating of the account when switching an account in the wallets
- [ ] Improve error messages shown in the admin pages on the front end.
       - For example when a non-admin tries to add itself as admin:
![image](https://github.com/Concordium/concordium-dapp-examples/assets/5469652/0b937dad-7dda-4fbb-9485-2cc8fecbcbcc)
- [ ] Make navbar not transparent to avoid overlap in text
![image](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/65d30ad5-f729-44c0-8137-791feb677671)
- [ ] Create a migration script that allows us to read out the current state-machine and admins as set in the smart contract and initialize a new smart contract instance with the same state. This enables us to easily roll out new versions of the hosted dapp without manually adding admins to a newly deployed contract.
