### ISSUE TITLE
Track-and-trace standard (CIS6)

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#82]
**Task description**

The standard defines the two events to enable tracking of items by external tools (e.g. block explorers).

```
pub struct ItemCreatedEvent {
    /// The item's id.
    pub item_id:      String,
    /// The item's metadata_url.
    pub metadata_url: Option<MetadataUrl>,
    /// Status when item was created.
    pub initial_status:      Status,
}

pub struct ItemStatusChangedEvent<A: Serial> {
    /// The item's id.
    pub item_id:         String,
    /// The item's new status.
    pub new_status:      Status,
    /// Any additional data encoded as generic bytes. Usecase-specific data can
    /// be included here such as temperature, longitude, latitude, ... .
    pub additional_data: A,
}
```

In preparation for the standard, the following changes were discussed:
- [x] Change `itemId` from a number to a `String` so that `Universally Unique Identifier (UUID)` can be used as well.
- [x] Add `initial_status` to the `CreateEvent` and display it at the front end.
- [x] Add `supports` (CIS0) function.
