### ISSUE TITLE
Front end for `compliant-reward-distribution-dapp`

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#96]
https://www.figma.com/design/2q2Rdmt5FuR0Pi0p6aRPDX/Mobile-Wallet-Master?node-id=1952-4651&t=ABvE3OShW7EVeb36-0

# Subtasks
- [x] Flows for generating the signatures/zk proofs with the Android CryptoX mobile wallet as well as the browser wallet to submit the tweet/zkproof to the backend.
- [x] Flows for admins to read data from the database.
- [x] Add dockerBuild/dockerCompose files to host the front-end. 
- [x] Release pipelines. 
- [  ] Apply Figma UI design.
