### ISSUE TITLE
Testnet faucet improvements

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-dapp-examples#97]
**Task description**

**Sub-tasks**
- [ ] Enable `TLS` support: Use `credentials.createSsl()` and the node with `https` connection (https://grpc.testnet.concordium.com:20000) in the Readme as an example for the `env` setting:
https://github.com/Concordium/concordium-dapp-examples/blob/main/testnet-faucet/src/lib/createGPRCClient.ts#L8
- [ ] Move usage limit check to backend - https://github.com/Concordium/concordium-dapp-examples/blob/main/testnet-faucet/src/pages/index.tsx#L127
- [ ] Enable support for hours instead of days: `NEXT_PUBLIC_USAGE_LIMIT_IN_DAYS=1` env should work with e.g .`0.25` for 6 hours.
